### ISSUE TITLE
ZeroPush error

### ISSUE THREAD

**Issue by SBYDeveloper** [panicinc/PunchClockServer#14]
When trying to deploy to Heroku im getting this error: The addon "zeropush" does not exist. Please ensure that the addon is spelled correctly. Please tell me how to bypass this.
![screen shot 2016-08-23 at 11 27 19 am](https://cloud.githubusercontent.com/assets/4661216/17885151/96289edc-6924-11e6-98b4-89899d3f2665.png)

**Comment by SBYDeveloper** [comment]
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.0.0
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/.........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Rubygems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
       Installing dotenv-deployment 0.0.2
       Installing multipart-post 1.2.0
       Installing thor 0.19.1
       Installing json 1.8.1 with native extensions
       Installing kgio 2.9.2 with native extensions
       Installing mime-types 2.2
       Installing pg 0.17.1 with native extensions
       Installing rack 1.5.2
       Installing raindrops 0.13.0 with native extensions
       Installing sequel 4.8.0
       Installing tilt 1.4.1
       Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES
       section: 'bacon'
       Bundler Output: Fetching gem metadata from https://rubygems.org/.........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Rubygems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
       Installing dotenv-deployment 0.0.2
       Installing multipart-post 1.2.0
       Installing thor 0.19.1
       Installing json 1.8.1 with native extensions
       Installing kgio 2.9.2 with native extensions
       Installing mime-types 2.2
       Installing pg 0.17.1 with native extensions
       Installing rack 1.5.2
       Installing raindrops 0.13.0 with native extensions
       Installing sequel 4.8.0
       Installing tilt 1.4.1
       Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES
       section: 'bacon'
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by foozmeat** [comment]
Hi, unfortunately PunchClock is unsupported. ZeroPush is likely no longer available from Heroku. I would recommend exploring any forks of this project that are available to see if someone has worked around the problem.
